### ISSUE TITLE
Feature Request: Run on a workspace

### ISSUE THREAD

**Issue by cpaika** [ToBinio/cargo-features-manager#13]
I have a workspace of multiple sub projects in Cargo.  The root `Cargo.toml` looks like this:
```
[workspace]
  resolver = "2"
members = [
    "app1",
    "app2",
    "common/lib1",
]
```

When I run `cargo features prune` from the root of the project I get:
`error : no dependencies were found`

I have to instead go into each subfolder to run `cargo features prune` for each subproject.  Would be great if it automatically (or with a flag) ran against all subprojects in the workspace when run at the root.

**Comment by ToBinio** [comment]
just released a [new version](https://crates.io/crates/cargo-features-manager/0.5.1) which adds basic workspace support

as far as I am concerned there is only one more problem #15 but I will probably not have time to fix it this weekend

btw thanks for opening this feature Request and for trying this project

**Comment by cpaika** [comment]
Awesome, thanks!
