### ISSUE TITLE
Features.toml

### ISSUE THREAD

**Issue by jayvdb** [ToBinio/cargo-features-manager#28]
I am not keen on yet another file.

Could this info be obtained from the Cargo.toml like cargo-machete does, and lots of other tools ; see https://github.com/bnjbvr/cargo-machete#false-positives

**Comment by ToBinio** [comment]
done in v0.8.0 see [Readme](https://github.com/ToBinio/cargo-features-manager?tab=readme-ov-file#false-positives)
