### ISSUE TITLE
prune global progress

### ISSUE THREAD

**Issue by jayvdb** [ToBinio/cargo-features-manager#29]
Currently the tool shows progress-type indicator for the crate it is currently considering.

It would be helpful to also see a global progress indicator, showing how many total combinations it has detected, and how many of them are completed.

i.e. give the user some sense of how long the entire process will take.

**Comment by ToBinio** [comment]
really like the idea so I quickly implemented it into [master](https://github.com/ToBinio/cargo-features-manager?tab=readme-ov-file#always-keep) would be great if you could have a quick look at it and see if it works as expected

**Comment by jayvdb** [comment]
It is good for medium size repos, but on larger ones, the global progress scrolls off the screen.
Still, I think this is good enough for now, because even for large projects, the user will have global progress at the beginning when they are most unsure about whether to let it run or not.

**Comment by AnthonyMichaelTDM** [comment]
I think the easiest "solution" would be to just print that progress indicator at the bottom

**Comment by ToBinio** [comment]
just publish [0.9.0](https://crates.io/crates/cargo-features-manager) that moves the progress bar to the bottom.
