### ISSUE TITLE
Unexpected removal of existing `default-features = false`

### ISSUE THREAD

**Issue by jayvdb** [ToBinio/cargo-features-manager#31]
First undesirable edit by `cargo features prune` on large work monorepo:

```diff
diff --git a/libs/foo1/Cargo.toml b/libs/foo1/Cargo.toml
-image = { default-features = false, features = ["jpeg"], workspace = true }
+image = { workspace = true , features = ["jpeg"] }
```

https://github.com/image-rs/image/blob/main/Cargo.toml has feature `default = ["rayon", "default-formats"]` , and I really don't want them.

**Comment by jayvdb** [comment]
Also the space before the comma in `workspace = true ,` is a bit unexpected.

**Comment by jayvdb** [comment]
Another case of prune adding features rather than removing them.  On https://github.com/Electron100/butane

```diff
diff --git a/butane_core/Cargo.toml b/butane_core/Cargo.toml
index 8aaebd0..8763204 100644
--- a/butane_core/Cargo.toml
+++ b/butane_core/Cargo.toml
@@ -41,7 +41,7 @@ proc-macro2 = { workspace = true }
 quote = { workspace = true }
 r2d2 = { optional = true, workspace = true }
 rand = { optional = true, workspace = true }
-regex = { version = "1.5", features = ["std"] }
+regex = { version = "1.5", features = ["perf", "std", "unicode-age", "unicode-bool", "unicode-gencat", "unicode-perl", "unicode-script", "unicode-segment"
], default-features = false }
 rusqlite = { workspace = true, optional = true }
 serde = { features = ["derive"], workspace = true }
 serde_json = { workspace = true }
```

**Comment by jayvdb** [comment]
hmm.  I re-ran it on butane, and now it is doing 
```diff
-regex = { version = "1.5", features = ["std"] }
+regex = "1.5"
```
Im guessing that the tool is doing multiple phases/edits, and my diff from an hour ago was of an intermediate state.

**Comment by ToBinio** [comment]
> First undesirable edit by `cargo features prune` on large work monorepo:
> 
> ```diff
> diff --git a/libs/foo1/Cargo.toml b/libs/foo1/Cargo.toml
> -image = { default-features = false, features = ["jpeg"], workspace = true }
> +image = { workspace = true , features = ["jpeg"] }
> ```
> 
> [image-rs/image@`main`/Cargo.toml](https://github.com/image-rs/image/blob/main/Cargo.toml?rgh-link-date=2024-05-03T16%3A51%3A13Z) has feature `default = ["rayon", "default-formats"]` , and I really don't want them.

could it be that your workspace dep has default features enabled? 

if so are you sure these features were ever disabled?
Based on my testing I think features enabled in the workspace are always on.


> Im guessing that the tool is doing multiple phases/edits, and my diff from an hour ago was of an intermediate state.

yes it currently works on the "live" Cargo.toml so it was probably a intermediate state

**Comment by ToBinio** [comment]
@jayvdb sry for the ping.

just want to make sure that this issue is cleared since I would like to release a new version.

**Comment by jayvdb** [comment]
I got half way through the process, and didnt see the problem.
It must have been an intermediate state.
