### ISSUE TITLE
`prune` does not check against tests

### ISSUE THREAD

**Issue by allada** [ToBinio/cargo-features-manager#38]
I noticed that if you run `cargo features prune` it will not ensure the feature changes are compatible with tests too.

I do understand that tests should probably use different features if they are not required by main, but does increase barrier to entry.

Maybe introduce a flag to have it also run against tests?

You can validate this by checking out this commit and remove this line, then run `cargo features prune`:
https://github.com/allada/nativelink-fork/blob/390490efbd86b3b16609fa0a30d067f5cae8ec8b/Cargo.toml#L72C1-L72C18

**Comment by ToBinio** [comment]
actually, I already do but it seems like `cargo test` does not run tests within a workspace.
will investigate this tomorrow or on Tuesday.  

Thanks for reporting & for using the tool!

**Comment by ToBinio** [comment]
just published a [new version](https://crates.io/crates/cargo-features-manager/0.8.3) that should fix this
