### ISSUE TITLE
Excessive disk space usage

### ISSUE THREAD

**Issue by jhelwig** [ToBinio/cargo-features-manager#40]
While poking at ways to possibly improve compilation times in [systeminit/si](https://github.com/systeminit/si), I started to take a look at `cargo-features-manager`. Unfortunately, I am unable to fully complete a `cargo features prune` run in the workspace as it fails part way through with a `No space left on device` error after `target/debug` grows to use 1.7 T.

```
❯ cargo features prune
workspace [84/399]

  config-file [2/2]
    toml [0/2]

  si-settings [5/5]
    config-file [0/5]

  🗃️ Workspace [77/392]
    async-nats [0/3]
    aws-config [0/6]
    aws-sdk-firehose [0/2]
    axum [0/11]
    base64 [0/2]
    blake3 [0/1]
    bytes [0/1]
    cacache [0/7]
    chrono [0/13]
    ciborium [0/1]
    clap [error-context,help,std,suggestions,usage,color/9]
    color-eyre [track-caller,color-spantrace,capture-spantrace,tracing-error/4]
    config [0/1]
    criterion [0/7]
    crossbeam-channel [0/1]
    crossbeam-queue [0/2]
    darling [0/1]
    deadpool [0/4]
    deadpool-postgres [0/1]
Error: ive_builder [0/1]
   0: No space left on device (os error 28)

Location:
   /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

❯ du -hs target/debug
1.7T
```

**Comment by ToBinio** [comment]
wow, I am very sorry to hear that but I don't really know how I could fix that.
`cargo features prune` simply runs `cargo build` & `cargo test` for every feature and checks if it works

I guess I could delete the `target/debug` folder after each build but that would dramatically worsen the time it took to complete 

do you generally have problems with space consumption? so could that be a cargo problem?

**Comment by jhelwig** [comment]
The size of the `target` directory isn't generally a problem. After `cargo clean` the usage in `target/debug` isn't exactly small, but it's really doesn't seem bad for a project of its size.

```
❯ du -hs target/debug
13G     target/debug
```

I think if there were an option for `cargo features prune` to optionally `cargo clean` between each crate it tries to prune the features of, it would help a lot. It would definitely still slow down the overall run time, but completing would definitely be faster than running out of disk space. 😆

**Comment by ToBinio** [comment]
just publish [0.9.0](https://crates.io/crates/cargo-features-manager) that includes `cargo features prune --clean <CLEAN>`

let me know if it works for you!

**Comment by jhelwig** [comment]
Thanks! I'll give it a try this afternoon/evening when I can kick it off to run uninterrupted for a while.

From a quick look at the commit (ecd179dc5876aaf370de1ed1c024a411ce192cee), it looks like the `--clean` option doesn't respect the `--dry-run` option, and will `cargo clean` regardless, depending on which `CleanLevel` is specified?

**Comment by ToBinio** [comment]
> From a quick look at the commit (https://github.com/ToBinio/cargo-features-manager/commit/ecd179dc5876aaf370de1ed1c024a411ce192cee), it looks like the --clean option doesn't respect the --dry-run option, and will cargo clean regardless, depending on which CleanLevel is specified?

yes, since `--dry-run` still builds the project I think it should still apply
`--dry-run` will just revert all the feature changes instead of keeping them.

**Comment by jhelwig** [comment]
Ok. I expected `--dry-run` to not do any compilation or test runs (basically to not make any changes on disk at all, even if it rolls them back), but I hadn't looked into the documentation for it yet.

`cargo features prune --clean dependency` was able to run to completion (took a little under 10 hours). Thanks for the quick response in adding the `--clean` option!

**Comment by ToBinio** [comment]
> Ok. I expected --dry-run to not do any compilation or test runs (basically to not make any changes on disk at all, even if it rolls them back), but I hadn't looked into the documentation for it yet.

I was thinking about copying the codebase and running it there but didn't get around to doing that so far

> cargo features prune --clean dependency was able to run to completion (took a little under 10 hours). Thanks for the quick response in adding the --clean option!

great to hear that! you are welcome!
